version: 2.1

executors:
  flutter-executor:
    docker:
      # Image Flutter stable hébergée sur Docker Hub
      - image: mobiledevops/flutter:3.22.0

jobs:
  build-apk:
    executor: flutter-executor
    steps:
      - checkout

      - run:
          name: Flutter Doctor
          command: flutter doctor -v

      - run:
          name: Get Dependencies
          command: flutter pub get

      - run:
          name: Build APK Release
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  build-pipeline:
    jobs:
      - build-apk
