org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=2
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=2
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
# Fix Already watching path: ne watch pas trop de dossiers en parallèle
kapt.incremental.apt=false
